---

- name: admin security groups
  ec2_group:
    state: present
    name: "{{env}}_{{item.key}}"
    description: "{{env}}_{{item.key}}"
    vpc_id: "{{ aws_vpc_id }}"
    region: "{{ aws_region }}"
    rules: "{{item.value.ingress | flatten}}"
    rules_egress: "{{item.value.egress | flatten}}"
  with_dict: "{{ security_rules }}"
  register: sgs
  vars:
    nat_all_traffic:
      - {group_name: "admin_nat", proto: 'tcp',   from_port: '1',   to_port: '65535'} # all tcp traffic to NAT
    vpc_all_traffic:
      - {cidr_ip: "{{aws_vpc_cidr}}", proto: 'tcp',   from_port: '1',   to_port: '65535'} # all tcp traffic
      - {cidr_ip: "{{aws_vpc_cidr}}", proto: 'udp',   from_port: '1',   to_port: '65535'} # all udp traffic
      - {cidr_ip: "{{aws_vpc_cidr}}", proto: 'icmp',  from_port: '-1',  to_port: '-1'}    # all icmp traffic
    world_http_https:
      - {cidr_ip: '0.0.0.0/0',              proto: 'tcp',     from_port: '80' , to_port: '80'}    # http to internet
      - {cidr_ip: '0.0.0.0/0',              proto: 'tcp',     from_port: '443', to_port: '443'}   # https to internet
    world_ping:
      - {cidr_ip: '0.0.0.0/0',              proto: 'icmp',    from_port: '-1',  to_port: '-1'}    # all icmp traffic
    world_ntp:
      - {cidr_ip: '0.0.0.0/0',          proto: 'udp',     from_port: '123',  to_port: '123'}  # ntp to internet
    security_rules:
      vpn:
        ingress:
          - {cidr_ip: "0.0.0.0/0",          proto: tcp, from_port: '22',    to_port: '22'}
          - {cidr_ip: "0.0.0.0/0",          proto: tcp, from_port: '1194',  to_port: '1194'}  # openvpn from internet
          - {cidr_ip: "0.0.0.0/0",          proto: udp, from_port: '1194',  to_port: '1194'}  # openvpn from internet
        egress:
          - "{{vpc_all_traffic}}"
          - "{{world_ntp}}"
          - "{{world_http_https}}"
      presentation:
        ingress:
          - {group_name: "admin_vpn", proto: tcp, from_port: '443', to_port: '443'} # https from vpn
        egress:
          - "{{vpc_all_traffic}}"
      application:
        ingress:
          - {group_name: "{{env}}_presentation", proto: tcp, from_port: '80',  to_port: '80'}   # http from presentation
          - {group_name: "{{env}}_presentation", proto: tcp, from_port: '443', to_port: '443'}  # https from presentation
          - {group_name: "admin_application",    proto: tcp, from_port: '22',  to_port: '22'}   # ssh from admin hosts
          - {group_name: "admin_vpn",            proto: tcp, from_port: '22',  to_port: '22'}   # ssh from vpn
          - {group_name: "admin_vpn",            proto: tcp, from_port: '443', to_port: '443'}
        egress: []
      data:
        ingress: []
        egress:
          - "{{vpc_all_traffic}}"

- name: tag admin security groups
  local_action:
    module: ec2_tag
    resource: "{{item.group_id}}"
    region: "{{ aws_region }}"
    state: present
    tags:
      Source: "{{vpc_tag_name}}"
      Name: "{{env}}_{{item.item.key}}"
      Env: "{{env}}"
  with_items: "{{ sgs.results }}"
